name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pytest
        run: |
          pip install pytest pytest-spec pytest-describe
      - name: Install psutil
        run: |
          pip install psutil
      - name: Run integration tests
        run: pytest --spec --color=yes test_battery.py

  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install behave
        run: pip install behave behave-webdriver
      - name: execute behave
        run: behave


